//First Exercise

let Num_2= 42;
const NumTOStr = String (Num_2);
console.log(`${typeof Num_1 }:${Num_2}`);
console.log(`${typeof NumTOStr}:${NumTOStr}`);

const STR = 25;
const STRTONUM = String (STR);
console.log(`${typeof STR }:${STR}`);
console.log(`${typeof STRTONUM}:${STRTONUM}`);




//Second Exercise

let str =10-"5";
console.log(str);

let main = 10+"5";
console.log (main);



//Third Exercise
const STr ="15.5";
const STrTOFLOAT = Number (STr);
console.log(STrTOFLOAT/5)
console.log(STrTOFLOAT*5)




//Fourth Exercise
let Str ="5";
let NuM ="3";
console.log(STr5 + NuM3);
console.log(STr5 - NuM3);



//Fifth Exercise
let Bool_1 =true;
let Num ="1";

console.log(Bool + Num1 );